# zh-Hans: Chinese (Simplified) 大陆简体
index:
  menu: 菜单
  tags: 标签
  friends: 友情链接
  about: 个人签名
  visitor: 最近访客
  more: more
  copy: 复制

toc:
  title: 文章目录
  hide: 隐藏目录
  show: 显示目录

visit_counter:
  site: 本博热度
  page: 本文热度

copyright_info:
  title: 本文标题
  author: 文章作者
  date: 发布时间
  updated: 最后更新
  url: 原始链接
  from: "原文:"
  by: "作者:"
  license: 许可协议
  cc: "署名-非商用-相同方式共享 3.0"
  notice: "转载请保留原文链接及作者。"

tooltip:
  tocButton: 点击按钮隐藏或者显示文章目录
  back2home: 回到主页
  nextPost: 下一篇
  prePost: 上一篇
  miniArchives: 文章列表
  back2top: 返回顶部
  jump2comments: 查看评论
  go2bottom: 转到底部
  copyPath: 点击复制文章链接
  Hexo: "快速、简洁且高效的博客框架"
  Yelee: 简而不减 Hexo 双栏博客主题

tag_cloud:
  already: 已有
  categories: 个分类，
  total: 共计
  tags: 个标签